version: '2'
services:
  nginx:
    build:
      context: ./
      dockerfile: docker/nginx/nginx.docker
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - php-fpm
  php-fpm:
    build:
      context: ./
      dockerfile: docker/php/php-fpm.docker
    volumes:
      - ./:/var/www
    links:
      - mysql
    environment:
      - "PHP_IDE_CONFIG=serverName=XdebugServer"
      - "DEBUG=1"
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
  php-cli:
    build:
      context: ./
      dockerfile: docker/php/php-cli.docker
    volumes:
      - ./:/var/www
    links:
      - mysql
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=mysql"
    tty: true
  mysql:
    image: mysql:5.7
    volumes:
      - ./storage/docker/mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=app"
    ports:
      - "33061:3306"
  node:
    image: node:16.13.2-slim
    volumes:
      - ./:/var/www
    working_dir: /var/www
    tty: true
